In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data.csv',encoding = 'latin1')

In [3]:
data

app_id  categories  \
0       B008JQPY2G  Kids,Games   
1       B008JQPY2G  Kids,Games   
2       B008JQPY2G  Kids,Games   
3       B008JQPY2G  Kids,Games   
4       B007JLQ5ZC       Games   
5       B007JLQ5ZC       Games   
6       B007JLQ5ZC       Games   
7       B007JLQ5ZC       Games   
8       B007JLQ5ZC       Games   
9       B007JLQ5ZC       Games   
10      B007JLQ5ZC       Games   
11      B007JLQ5ZC       Games   
12      B007JLQ5ZC       Games   
13      B007JLQ5ZC       Games   
14      B007JLQ5ZC       Games   
15      B007JLQ5ZC       Games   
16      B007JLQ5ZC       Games   
17      B007JLQ5ZC       Games   
18      B007JLQ5ZC       Games   
19      B00HFFV8AE       Games   
20      B00HFFV8AE       Games   
21      B00HFFV8AE       Games   
22      B00HFFV8AE       Games   
23      B00HFFV8AE       Games   
24      B00HFFV8AE       Games   
25      B00HFFV8AE       Games   
26      B00HFFV8AE       Games   
27      B00HFFV8AE       Games   
28      B00HFFV8AE       Games   
29      B017G01SFM       Games   
...            ...         ...   
501727  B007D21OC6       Games   
501728  B00PJ5AUCO       Games   
501729  B018LSIQI0       Games   
501730  B00BTHK13Y       Games   
501731  B006BDHAX0       Games   
501732  B00T2HB7VI       Games   
501733  B008TQ16OG       Games   
501734  B00B2WV3JC       Games   
501735  B004Z9ZNTK       Games   
501736  B009NG7R3K       Games   
501737  B008AM3I72       Games   
501738  B00992CF6W       Games   
501739  B00NWLIW0E       Games   
501740  B00YQ4IRBK       Games   
501741  B0066T8SDU       Games   
501742  B008Y212PI       Games   
501743  B00QSCXUY2       Games   
501744  B00OAJ352W       Games   
501745  B00N35P5MW       Games   
501746  B00AESN8XY       Games   
501747  B006R6712G       Games   
501748  B00H9ETJYI       Games   
501749  B00992CF6W       Games   
501750  B009LGJW58       Games   
501751  B00PJ5AUCO       Games   
501752  B00DDZM0GQ       Games   
501753  B005NDKHR0       Games   
501754  B00IVCNW0Y       Games   
501755  B0085YNML2       Games   
501756  B00884GR0W       Games   

                                              description       review_id  \
0       Attention Monsters Fans... Now you can Get the...  R295U1EYQDU4CN   
1       Attention Monsters Fans... Now you can Get the...  R2Z8UUF4V7ERKX   
2       Attention Monsters Fans... Now you can Get the...  R35VWHNI4UXNIP   
3       Attention Monsters Fans... Now you can Get the...   R7LQK4NGD2ATF   
4       Knife Thrower lets you perform daring knife th...  R1GJGQTM2E1C39   
5       Knife Thrower lets you perform daring knife th...  R1J0XBTNHRUXWA   
6       Knife Thrower lets you perform daring knife th...  R1U9EWSJAX82ZV   
7       Knife Thrower lets you perform daring knife th...  R2ETR1BQIZYT3U   
8       Knife Thrower lets you perform daring knife th...   R2K45B7YFI8Q8   
9       Knife Thrower lets you perform daring knife th...  R2OC1QH86Z8NQC   
10      Knife Thrower lets you perform daring knife th...  R2QDBFDE7OZZJ9   
11      Knife Thrower lets you perform daring knife th...  R2UUXV4N4MKDUW   
12      Knife Thrower lets you perform daring knife th...  R3ESEGT1056X3O   
13      Knife Thrower lets you perform daring knife th...  R3OW3C8RXEFNOD   
14      Knife Thrower lets you perform daring knife th...  R3PMC1TYI27A1B   
15      Knife Thrower lets you perform daring knife th...   R870RZV5O40AF   
16      Knife Thrower lets you perform daring knife th...   RAMJEF6M9ZC92   
17      Knife Thrower lets you perform daring knife th...   RENTSM24XW4PB   
18      Knife Thrower lets you perform daring knife th...   REOY3MUEYO7D3   
19      Dragged by her parents, a young and rebellious...  R14ZFLM6H02X2G   
20      Dragged by her parents, a young and rebellious...  R1YYZ1CUF1251B   
21      Dragged by her parents, a young and rebellious...  R2U2IH4DK0NTTL   
22      Dragged by her parents, a young and rebellious...  R37KLNVC2NI4BR   
23      Dragged by her parents, a young and rebellious.

In [4]:
aid = data['app_id'].values.tolist()
rating = data['star_rating'].values.tolist()
rid = data['reviewer'].values.tolist()

In [5]:
items = data.groupby('app_id').groups
users = data.groupby('reviewer').groups

In [6]:
import networkx as nx
from networkx.algorithms import bipartite
B=nx.Graph()
B.add_nodes_from(list(items.keys()), bipartite=0)
B.add_nodes_from(list(users.keys()), bipartite=1)
for i in range(len(rid)):
    try:
        B.add_edge(aid[i], rid[i], weight=rating[i])
    except:
        pass

In [7]:
from networkx.algorithms.bipartite import biadjacency_matrix

r_order = list(set(aid))
c_order = list(set(rid))
mat = biadjacency_matrix(B, row_order = r_order, column_order = c_order)

In [8]:
mat

<7986x351387 sparse matrix of type '<class 'numpy.float64'>'
	with 501669 stored elements in Compressed Sparse Row format>

In [9]:
from collections import defaultdict
globalAverage = data['star_rating'].mean()

In [10]:
userRatings = defaultdict(list)
itemRatings = defaultdict(list)
for i in range(len(rid)):
    user = rid[i]
    item = aid[i]
    userRatings[user].append(rating[i])
    itemRatings[item].append(rating[i])
userAverage = {}
for u in userRatings:
    userAverage[u] = sum(userRatings[u]) / len(userRatings[u])
itemAverage = {}
for i in itemRatings:
    itemAverage[i] = sum(itemRatings[i]) / len(itemRatings[i])

In [11]:
def find_non_zero_entry(m):
    l1 = m.nonzero()[0]
    l2 = m.nonzero()[1]
    l = []
    for i in range(len(l1)):
        l.append((l1[i],l2[i]))
    return l
l = find_non_zero_entry(mat)

In [24]:
Y = []
userAvg = []
itemAvg = []
userLoyalty = []
itemPopularity = []
for pair in l:
    Y.append(mat[pair[0], pair[1]])
    userAvg.append(sum(userRatings[c_order[pair[1]]])/len(userRatings[c_order[pair[1]]]))
    itemAvg.append(sum(itemRatings[r_order[pair[0]]])/len(itemRatings[r_order[pair[0]]]))
    userLoyalty.append(len(userRatings[c_order[pair[1]]]))
    itemPopularity.append(len(itemRatings[r_order[pair[0]]]))

In [25]:
df_train = pd.DataFrame(np.array([Y,userAvg,itemAvg, userLoyalty, itemPopularity]).T, columns=['Y', 'userAvg', 'itemAvg', 'userLoyalty', 'itemPopularity'])
import statsmodels.api as sm
model = sm.OLS(df_train['Y'], df_train[['userAvg', 'itemAvg', 'userLoyalty', 'itemPopularity']]).fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.978
Model:                            OLS   Adj. R-squared:                  0.978
Method:                 Least Squares   F-statistic:                 5.474e+06
Date:                Sun, 11 Dec 2016   Prob (F-statistic):               0.00
Time:                        04:01:25   Log-Likelihood:            -4.8758e+05
No. Observations:              501669   AIC:                         9.752e+05
Df Residuals:                  501665   BIC:                         9.752e+05
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [95.0% Conf. Int.]
----------------------------------------------------------------------------------
userAvg            0.9479      0.001   1191.

In [19]:
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_train[['X1', 'X2', 'X3', 'X4']], df_train['Y'], test_size=0.3, random_state=1)
lr = LogisticRegression(C=1000.0, random_state=0)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
lr_avg_error = ((y_test - y_pred)*(y_test - y_pred)).sum()/len(y_pred)
print('Logistic regression average error: %.6f'% lr_avg_error)
print('Number of misclassified samples: %d' % (y_test != y_pred).sum())
from sklearn.metrics import accuracy_score

print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))    

print('Coefficients: \n', lr.coef_)

Logistic regression average error: 1.185368
Number of misclassified samples: 51498
Accuracy: 0.66
Coefficients: 
 [[ -1.73760212e+00   5.55775301e-01   4.44080324e-03  -1.70235589e-05]
 [ -5.68375225e-01  -2.59253834e-01   3.13732213e-03  -1.19256931e-05]
 [ -3.37900727e-01  -2.68677833e-01   3.06546816e-03  -8.31843069e-06]
 [ -9.35581082e-02  -2.49807296e-01   6.98525534e-04  -1.04494804e-05]
 [  1.57512547e+00  -1.31104040e+00  -2.74177598e-03   2.76476755e-05]]


In [22]:
regr = LinearRegression()
regr.fit(X_train, y_train)
y_train_pred = regr.predict(X_train)
y_test_pred = regr.predict(X_test)

regr_avg_error = (((y_test - y_test_pred)*(y_test - y_test_pred)).sum())/len(y_test_pred)
print('Linear regression average error: %.6f'% regr_avg_error)
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

print('MSE train: %.3f, test: %.3f' %(mean_squared_error(y_train, y_train_pred),
                                      mean_squared_error(y_test, y_test_pred)))
 
print('R^2 train: %.3f, test: %.3f' %(r2_score(y_train, y_train_pred),
                                      r2_score(y_test, y_test_pred)))
print('Coefficients: \n', regr.coef_)

Linear regression average error: 0.399457
MSE train: 0.396, test: 0.399
R^2 train: 0.792, test: 0.791
Coefficients: 
 [  9.57774524e-01   2.45709980e-01   3.19432991e-04  -1.49464901e-06]


In [17]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(criterion='entropy',
                                n_estimators=100, 
                                random_state=1,
                                n_jobs=2)
forest.fit(X_train, y_train)

y_pred_forest = forest.predict(X_test)
rf_avg_error = ((y_test - y_pred_forest)*(y_test - y_pred_forest)).sum()/len(y_pred_forest)
print('RF Misclassified samples: %d'% (y_test != y_pred_forest).sum())
print('RF average error: %.6f'% rf_avg_error)
from sklearn.metrics import accuracy_score

print('RF Accuracy: %.2f'% accuracy_score(y_test, y_pred_forest))

RF Misclassified samples: 25737
RF average error: 0.645105
RF Accuracy: 0.83


In [21]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
nb_avg_error = ((y_test - y_pred1)*(y_test - y_pred1)).sum()/len(y_pred1)
print('Naive Bayes Misclassified samples: %d'% (y_test != y_pred1).sum())
print('Naive Bayes average error: %.6f'% nb_avg_error)
from sklearn.metrics import accuracy_score
print('Naive Bayes Accuracy: %.2f'% accuracy_score(y_test, y_pred1))

Naive Bayes Misclassified samples: 45377
Naive Bayes average error: 0.660474
Naive Bayes Accuracy: 0.70


In [23]:
data = pd.read_csv('data.csv',encoding = 'latin1')
app_id = data['app_id']


app_id  categories  \
0       B008JQPY2G  Kids,Games   
1       B008JQPY2G  Kids,Games   
2       B008JQPY2G  Kids,Games   
3       B008JQPY2G  Kids,Games   
4       B007JLQ5ZC       Games   
5       B007JLQ5ZC       Games   
6       B007JLQ5ZC       Games   
7       B007JLQ5ZC       Games   
8       B007JLQ5ZC       Games   
9       B007JLQ5ZC       Games   
10      B007JLQ5ZC       Games   
11      B007JLQ5ZC       Games   
12      B007JLQ5ZC       Games   
13      B007JLQ5ZC       Games   
14      B007JLQ5ZC       Games   
15      B007JLQ5ZC       Games   
16      B007JLQ5ZC       Games   
17      B007JLQ5ZC       Games   
18      B007JLQ5ZC       Games   
19      B00HFFV8AE       Games   
20      B00HFFV8AE       Games   
21      B00HFFV8AE       Games   
22      B00HFFV8AE       Games   
23      B00HFFV8AE       Games   
24      B00HFFV8AE       Games   
25      B00HFFV8AE       Games   
26      B00HFFV8AE       Games   
27      B00HFFV8AE       Games   
28      B00HFFV8AE       Games   
29      B017G01SFM       Games   
...            ...         ...   
501727  B007D21OC6       Games   
501728  B00PJ5AUCO       Games   
501729  B018LSIQI0       Games   
501730  B00BTHK13Y       Games   
501731  B006BDHAX0       Games   
501732  B00T2HB7VI       Games   
501733  B008TQ16OG       Games   
501734  B00B2WV3JC       Games   
501735  B004Z9ZNTK       Games   
501736  B009NG7R3K       Games   
501737  B008AM3I72       Games   
501738  B00992CF6W       Games   
501739  B00NWLIW0E       Games   
501740  B00YQ4IRBK       Games   
501741  B0066T8SDU       Games   
501742  B008Y212PI       Games   
501743  B00QSCXUY2       Games   
501744  B00OAJ352W       Games   
501745  B00N35P5MW       Games   
501746  B00AESN8XY       Games   
501747  B006R6712G       Games   
501748  B00H9ETJYI       Games   
501749  B00992CF6W       Games   
501750  B009LGJW58       Games   
501751  B00PJ5AUCO       Games   
501752  B00DDZM0GQ       Games   
501753  B005NDKHR0       Games   
501754  B00IVCNW0Y       Games   
501755  B0085YNML2       Games   
501756  B00884GR0W       Games   

                                              description       review_id  \
0       Attention Monsters Fans... Now you can Get the...  R295U1EYQDU4CN   
1       Attention Monsters Fans... Now you can Get the...  R2Z8UUF4V7ERKX   
2       Attention Monsters Fans... Now you can Get the...  R35VWHNI4UXNIP   
3       Attention Monsters Fans... Now you can Get the...   R7LQK4NGD2ATF   
4       Knife Thrower lets you perform daring knife th...  R1GJGQTM2E1C39   
5       Knife Thrower lets you perform daring knife th...  R1J0XBTNHRUXWA   
6       Knife Thrower lets you perform daring knife th...  R1U9EWSJAX82ZV   
7       Knife Thrower lets you perform daring knife th...  R2ETR1BQIZYT3U   
8       Knife Thrower lets you perform daring knife th...   R2K45B7YFI8Q8   
9       Knife Thrower lets you perform daring knife th...  R2OC1QH86Z8NQC   
10      Knife Thrower lets you perform daring knife th...  R2QDBFDE7OZZJ9   
11      Knife Thrower lets you perform daring knife th...  R2UUXV4N4MKDUW   
12      Knife Thrower lets you perform daring knife th...  R3ESEGT1056X3O   
13      Knife Thrower lets you perform daring knife th...  R3OW3C8RXEFNOD   
14      Knife Thrower lets you perform daring knife th...  R3PMC1TYI27A1B   
15      Knife Thrower lets you perform daring knife th...   R870RZV5O40AF   
16      Knife Thrower lets you perform daring knife th...   RAMJEF6M9ZC92   
17      Knife Thrower lets you perform daring knife th...   RENTSM24XW4PB   
18      Knife Thrower lets you perform daring knife th...   REOY3MUEYO7D3   
19      Dragged by her parents, a young and rebellious...  R14ZFLM6H02X2G   
20      Dragged by her parents, a young and rebellious...  R1YYZ1CUF1251B   
21      Dragged by her parents, a young and rebellious...  R2U2IH4DK0NTTL   
22      Dragged by her parents, a young and rebellious...  R37KLNVC2NI4BR   
23      Dragged by her parents, a young and rebellious.

In [34]:
def matrix_factorization(R, P, Q, K, entries, steps=2000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for entry in entries:
            i = entry[0]
            j = entry[1]
            eij = R[i, j] - np.dot(P[i,:],Q[:,j])
            for k in range(K):
                P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        e = 0
        for entry in entries:
            i = entry[0]
            j = entry[1]
            e = e + pow(R[i,j] - np.dot(P[i,:],Q[:,j]), 2)
            for k in range(K):
                e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001:
            break
    return P, Q.T

In [32]:
R = mat
N = R.shape[0]
M = R.shape[1]
K = 20
P = np.random.rand(N,K)+ 1
Q = np.random.rand(M,K)+ 1

In [35]:
nP, nQ = matrix_factorization(R, P, Q, K, l)

KeyboardInterrupt: 